@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.risttahukas.moremobheads.enchantment;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;