@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.risttahukas.moremobheads.effect.headeffects;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;