@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.risttahukas.moremobheads.effect.activeheadeffects;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;