@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.risttahukas.moremobheads.event;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;