@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package net.risttahukas.moremobheads.capability;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;